services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_data:/app/static
      - media_data:/app/media
    expose:
      - "8000"
    command: >
      sh -c "python manage.py makemigrations userauth subscription api api_monitor payments monitoring prediction apistatus contact newsletter monitor neural userprofile activity rigsdata reports settings gis modelbuilder config insurance &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py add_rigs &&
             python manage.py add_subscription_plans &&
             python manage.py create_profiles &&
             python manage.py createprofile &&
             gunicorn --bind 0.0.0.0:8000 auth.wsgi:application"
    environment:
      - DEBUG=${DEBUG}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - CUDA_VISIBLE_DEVICES=""
      - DJANGO_SETTINGS_MODULE=auth.settings
    restart: always


  redis:
    image: redis:alpine
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  data_sender:
    build:
      context: .
      dockerfile: data_sender.Dockerfile
    depends_on:
      - redis
      - django
    command: >
      sh -c "python sender/send_data.py"
    environment:
      - REDIS_URL=redis://redis:6379
      - API_HOST=http://django:8000
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    restart: always

volumes:
  static_data:
  media_data: