# Generated by Django 5.1.8 on 2025-04-20 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coverage_limit', models.DecimalField(decimal_places=3, max_digits=12)),
                ('claim_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('target_audience', models.CharField(blank=True, max_length=255, null=True)),
                ('duration_months', models.PositiveIntegerField(default=12)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insured', models.BooleanField(default=False)),
                ('active_policies', models.PositiveIntegerField(default=0)),
                ('last_claim_date', models.DateField(blank=True, null=True)),
                ('total_claimed', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('active_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insured_users', to='insurance.insuranceplan')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_profile', to='userprofile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InsurancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('insurance_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='insurance.insuranceprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('claim_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('insurance_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance.insuranceprofile')),
            ],
        ),
    ]
