# Generated by Django 5.1.8 on 2025-04-20 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitor', '0001_initial'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ml_model', models.CharField(choices=[('SVM', 'Support Vector Machine'), ('Random Forest', 'Random Forest'), ('Neural Network', 'Neural Network'), ('KNN', 'K-Nearest Neighbors'), ('Linear Regression', 'Linear Regression'), ('Decision Tree', 'Decision Tree')], default='Random Forest', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_models', to='userprofile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ModelFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('custom_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='modelbuilder.custommodel')),
            ],
        ),
        migrations.CreateModel(
            name='RigAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('custom_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rig_assignments', to='modelbuilder.custommodel')),
                ('rig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.rig')),
            ],
        ),
    ]
