# Generated by Django 5.1.8 on 2025-04-20 09:59

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_level_threshold', models.FloatField(help_text='Critical water level threshold in mm.')),
                ('temperature_threshold', models.FloatField(help_text='Critical temperature threshold in °C.')),
                ('humidity_threshold', models.FloatField(help_text='Critical humidity threshold in %.')),
            ],
            options={
                'db_table': 'criticalthresholds',
            },
        ),
        migrations.CreateModel(
            name='Rig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(default='Unknown', max_length=100)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'rigs',
            },
        ),
        migrations.CreateModel(
            name='RigArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('area_polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'db_table': 'rig_areas',
            },
        ),
        migrations.CreateModel(
            name='SyncActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('table_name', models.CharField(max_length=255)),
                ('records_updated', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'syncactivity',
            },
        ),
        migrations.CreateModel(
            name='WaterLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('rig', models.CharField(max_length=255)),
                ('level', models.FloatField(default=0.0)),
                ('temperature', models.FloatField(default=0.0)),
                ('humidity', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'waterlevels',
            },
        ),
        migrations.CreateModel(
            name='PredictedWaterLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('predicted_level', models.FloatField()),
                ('model_name', models.CharField(max_length=50)),
                ('accuracy', models.FloatField()),
                ('rig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.rig')),
            ],
            options={
                'db_table': 'predictedwaterlevels',
            },
        ),
        migrations.AddField(
            model_name='rig',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rigs', to='monitor.rigarea'),
        ),
        migrations.CreateModel(
            name='WaterLevelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(blank=True, editable=False, max_length=24, null=True, unique=True)),
                ('level', models.FloatField(default=0.0)),
                ('temperature', models.FloatField(default=0.0)),
                ('humidity', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField()),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('rig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.rig')),
            ],
            options={
                'db_table': 'waterleveldata',
            },
        ),
    ]
