# Generated by Django 5.1.8 on 2025-04-20 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscription', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('subscription_status', models.BooleanField(default=False)),
                ('subscription_level', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('category', models.CharField(choices=[('Student', 'Student'), ('Professional', 'Professional'), ('Associate', 'Associate')], default='Student', max_length=20)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='subscription.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
